dbt_retail_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5441
      user: "{{ env_var('CI_DB_USER', env_var('DBT_USER')) }}"
      password: "{{ env_var('CI_DB_PASSWORD', env_var('DEV_DB_PASSWORD')) }}"
      dbname: retail_ci
      schema: "{{ env_var('DBT_USER') }}"
      threads: 4
